name: open_budget
description: "Open Budget is open-source, cross-platform budgeting application."
publish_to: 'none'
version: 0.5.2+10

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.3
  drift_dev: ^2.29.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/openbudget_icon.png"
  windows: 
    generate: true
    image_path: "assets/icon/openbudget_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/openbudget_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
